### ISSUE TITLE
Add descriptions to abbreviations in the architecture diagram

### ISSUE THREAD

**Issue by livelybug** [octopus-network/octopus-docs#1]
In the architecture diagram(src/en/octopus/Octopus_Architecture.png), there are some abbreviations: D,S, CEXs, V, RT, BFT, N, and Octopus DAO.

Some readers may not understand all of these abbreviations very well.
It would be more reader-friendly if these abbreviations have corresponding descriptions or references.
@lesterli

**Comment by lesterli** [comment]
Added, https://github.com/octopus-network/octopus-docs/blob/main/src/general/octopus-overview.md
