### ISSUE TITLE
content to update?

### ISSUE THREAD

**Issue by livelybug** [octopus-network/octopus-docs#3]
In files: 
* src/appchain/integrate.md
* src/en/appchain/integrate.md

The following is inconsistent with the code in Barnacle:
```
	type AppchainId = AppchainId;
	type Motherchain = Motherchain;
	const RELAY_CONTRACT_NAME: &'static [u8] = b"dev-1618284355026-5339538";
```
------------------------------------

How to get the value ```oct-relay.testnet``` from our testnet?

---------------------------------------
> You can see the last commit of [Barnacle](https://github.com/octopus-network/barnacle) for the entire changes.

Update with a specific commit.

**Comment by lesterli** [comment]
From the web page, e.g. https://testnet.oct.network/
